   <x-app-layout>
       <x-hero></x-hero>
       <x-hero1></x-hero1>
       <x-hero2></x-hero2>
       <x-hero3></x-hero3>
       <x-hero4></x-hero4>
       <x-hero5></x-hero5>
       <x-hero6></x-hero6>
   </x-app-layout>
